// Package {{ .Package }} provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: {{ .Version }}
package {{ .Package }}

{{ if .IsRoot }}
var {{ .PrivateSlug }}Directory *{{ .PrefixedPublicSlug }}Directory

func {{ .PrivateSlug }}() *{{ .PrefixedPublicSlug }}Directory {
    if {{ .PrivateSlug }}Directory == nil {
        {{ .PrivateSlug }}Directory = &{{ .PrefixedPublicSlug }}Directory{}
    }

    return {{ .PrivateSlug }}Directory
}
{{ end }}

type {{ .PrefixedPublicSlug }}Directory struct {
	{{ range .Directories }}{{ .PrivateSlug }}Directory *{{ .PrefixedPublicSlug }}Directory
	{{ end }}
}
{{ range .Queries }}
func (d *{{ $.PrefixedPublicSlug }}Directory) {{ .PublicSlug }}{{ .QueryGetterSuffix }}() string {
    return {{ .GetQuotedContent }}
}
{{ if $.IsRoot }}
func {{ .PublicSlug }}{{ .QueryGetterSuffix }}() string {
    return {{ $.PrivateSlug }}().{{ .PublicSlug }}{{ .QueryGetterSuffix }}()
}
{{ end }}
{{ end }}
{{ range .Directories }}
func (d *{{ $.PrefixedPublicSlug }}Directory) {{ .PublicSlug }}() *{{ .PrefixedPublicSlug }}Directory {
    if d.{{ .PrivateSlug }}Directory == nil {
        d.{{ .PrivateSlug }}Directory = &{{ .PrefixedPublicSlug }}Directory{}
    }

	return d.{{ .PrivateSlug }}Directory
}
{{ if $.IsRoot }}
func {{ .PublicSlug }}() *{{ .PrefixedPublicSlug }}Directory {
    return {{ $.PrivateSlug }}().{{ .PublicSlug }}()
}
{{ end }}
{{ end }}
