// Package {{ .Package }} provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: {{ .Version }}
package {{ .Package }}

{{ if .IsRoot }}
var {{ .PrivateSlug }}Directory *{{ .PrefixedPublicSlug }}Directory

func {{ .PublicSlug }}() *{{ .PrefixedPublicSlug }}Directory {
    if {{ .PrivateSlug }}Directory == nil {
        {{ .PrivateSlug }}Directory = &{{ .PrefixedPublicSlug }}Directory{}
    }

    return {{ .PrivateSlug }}Directory
}
{{ end }}

type {{ .PrefixedPublicSlug }}Directory struct {
	{{ range .Queries }}{{ .PrivateSlug }}Query string
	{{ end }}
	{{ range .Directories }}{{ .PrivateSlug }}Directory *{{ .PrefixedPublicSlug }}Directory
	{{ end }}
}
{{ range .Queries }}
func (d *{{ $.PrefixedPublicSlug }}Directory) {{ .PublicSlug }}Query() string {
    return {{ .GetQuotedContent }}
}
{{ end }}
{{ range .Directories }}
func (d *{{ $.PrefixedPublicSlug }}Directory) {{ .PublicSlug }}() *{{ .PrefixedPublicSlug }}Directory {
    if d.{{ .PrivateSlug }}Directory == nil {
        d.{{ .PrivateSlug }}Directory = &{{ .PrefixedPublicSlug }}Directory{}
    }

	return d.{{ .PrivateSlug }}Directory
}
{{ end }}
