include:
  - .gitlab/gocache.yml

build:
  extends: .go_cache
  stage: build
  image: golang:1.24-alpine
  needs:
    - validate
  rules:
    - if: ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event')
      when: on_success
    - when: manual
  before_script:
    - apk add --no-cache make git
  script:
    - make build
