// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: test_version (revision test_revision, built at 20250701000000)
package queries

type OrdersDirectory struct {
	changeStatusQuery string
	createOrderQuery  string
}

func (d *OrdersDirectory) ChangeStatusQuery() string {
	return `UPDATE orders SET status = $1 WHERE id = $2;`
}

func (d *OrdersDirectory) CreateOrderQuery() string {
	return `INSERT INTO orders (id, name, price) VALUES ($1, $2, $3);`
}
