// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20250710080424)
// Source: example/sql/orders
package queries

type OrdersDirectory struct {
}

// ChangeStatusQuery returns query from the example/sql/orders/change-status.sql file.
func (d *OrdersDirectory) ChangeStatusQuery() string {
	return `UPDATE orders SET status = $1 WHERE id = $2;`
}

// CreateOrderQuery returns query from the example/sql/orders/create-order.sql file.
func (d *OrdersDirectory) CreateOrderQuery() string {
	return `INSERT INTO orders (id, name, price) VALUES ($1, $2, $3);`
}
