// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20251003081857)
// Source: example/sql
package queries

var queriesDirectory *QueriesDirectory

func queries() *QueriesDirectory {
	if queriesDirectory == nil {
		queriesDirectory = &QueriesDirectory{}
	}

	return queriesDirectory
}

type QueriesDirectory struct {
	ordersDirectory  *OrdersDirectory
	queriesDirectory *QueriesQueriesDirectory
	usersDirectory   *UsersDirectory
}

// VersionQuery returns query from the example/sql/version.sql file.
func (d *QueriesDirectory) VersionQuery() string {
	return `SELECT version FROM app_info;`
}

func VersionQuery() string {
	return queries().VersionQuery()
}

func (d *QueriesDirectory) Orders() *OrdersDirectory {
	if d.ordersDirectory == nil {
		d.ordersDirectory = &OrdersDirectory{}
	}

	return d.ordersDirectory
}

func Orders() *OrdersDirectory {
	return queries().Orders()
}

func (d *QueriesDirectory) Queries() *QueriesQueriesDirectory {
	if d.queriesDirectory == nil {
		d.queriesDirectory = &QueriesQueriesDirectory{}
	}

	return d.queriesDirectory
}

func Queries() *QueriesQueriesDirectory {
	return queries().Queries()
}

func (d *QueriesDirectory) Users() *UsersDirectory {
	if d.usersDirectory == nil {
		d.usersDirectory = &UsersDirectory{}
	}

	return d.usersDirectory
}

func Users() *UsersDirectory {
	return queries().Users()
}
