// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20250710080424)
// Source: example/sql/queries
package queries

type QueriesQueriesDirectory struct {
}

// MiscQuery returns query from the example/sql/queries/misc.sql file.
func (d *QueriesQueriesDirectory) MiscQuery() string {
	return `-- Directory with a name equal to package name.
-- Also, this file contains a '` + "```" + `' quote symbol.
-- And the another` + "`" + `s one.
SELECT '1';`
}
