// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble version  (revision , built at ) DO NOT EDIT.
package queries

var queriesDirectory *QueriesDirectory

func Queries() *QueriesDirectory {
	if queriesDirectory == nil {
		queriesDirectory = &QueriesDirectory{}
	}

	return queriesDirectory
}

type QueriesDirectory struct {
	versionQuery string

	ordersDirectory  *OrdersDirectory
	queriesDirectory *QueriesQueriesDirectory
	usersDirectory   *UsersDirectory
}

func (d *QueriesDirectory) VersionQuery() string {
	return `SELECT version FROM app_info;`
}

func (d *QueriesDirectory) Orders() *OrdersDirectory {
	if d.ordersDirectory == nil {
		d.ordersDirectory = &OrdersDirectory{}
	}

	return d.ordersDirectory
}

func (d *QueriesDirectory) Queries() *QueriesQueriesDirectory {
	if d.queriesDirectory == nil {
		d.queriesDirectory = &QueriesQueriesDirectory{}
	}

	return d.queriesDirectory
}

func (d *QueriesDirectory) Users() *UsersDirectory {
	if d.usersDirectory == nil {
		d.usersDirectory = &UsersDirectory{}
	}

	return d.usersDirectory
}
