// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: test_version (revision test_revision, built at )
package queries

type QueriesQueriesDirectory struct {
	miscQuery string
}

func (d *QueriesQueriesDirectory) MiscQuery() string {
	return `-- Directory with a name equal to package name.
-- Also, this file contains a '` + "```" + `' quote symbol.
-- And the another` + "`" + `s one.
SELECT '1';`
}
