// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20250702134550)
package queries

type UsersDirectory struct {
	singleUserDirectory *UsersSingleUserDirectory
}

func (d *UsersDirectory) GetListQuery() string {
	return `SELECT * FROM users;`
}

func (d *UsersDirectory) SingleUser() *UsersSingleUserDirectory {
	if d.singleUserDirectory == nil {
		d.singleUserDirectory = &UsersSingleUserDirectory{}
	}

	return d.singleUserDirectory
}
