// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20250701000000)
package queries

type UsersSingleUserDirectory struct {
	getUserDataQuery string
}

func (d *UsersSingleUserDirectory) GetUserDataQuery() string {
	return `SELECT * FROM users WHERE id = $1;`
}
