// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble version  (revision , built at ) DO NOT EDIT.
package queries

type UsersSingleUserDirectory struct {
	getUserDataQuery string
}

func (d *UsersSingleUserDirectory) GetUserDataQuery() string {
	return `SELECT * FROM users WHERE id = $1;`
}
