// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble DO NOT EDIT.
// Sqlamble version: unknown (revision unknown, built at 20250710080424)
// Source: example/sql/users/single-user
package queries

type UsersSingleUserDirectory struct {
}

// GetUserDataQuery returns query from the example/sql/users/single-user/get-user-data.sql file.
func (d *UsersSingleUserDirectory) GetUserDataQuery() string {
	return `SELECT * FROM users WHERE id = $1;`
}
