// Package queries provides structured SQL queries.
//
// Code generated by github.com/kukymbr/sqlamble version  (revision , built at ) DO NOT EDIT.
package queries

type UsersDirectory struct {
	getListQuery string

	singleUserDirectory *UsersSingleUserDirectory
}

func (d *UsersDirectory) GetListQuery() string {
	return `SELECT * FROM users;`
}

func (d *UsersDirectory) SingleUser() *UsersSingleUserDirectory {
	if d.singleUserDirectory == nil {
		d.singleUserDirectory = &UsersSingleUserDirectory{}
	}

	return d.singleUserDirectory
}
